name: path-to-the-future_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_9
  - blas=1.0=mkl
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py37_0
  - cffi=1.14.3=py37he30daa8_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cycler=0.10.0=py37_0
  - cython=0.29.21=py37he6710b0_0
  - dbus=1.13.16=hb2f20db_0
  - expat=2.2.9=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_9
  - git=2.23.0=pl526hacde149_0
  - glib=2.65.0=h3eb4bd4_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_9
  - icu=58.2=he6710b0_3
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.2.0=py37hfd86e86_0
  - krb5=1.18.2=h173b8e3_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.71.1=h20c2e04_1
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_1
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py37h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.1=py37hfd86e86_0
  - numpy=1.19.1=py37hbc911f0_0
  - numpy-base=1.19.1=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=h7b6447c_0
  - pandas=1.1.2=py37he6710b0_0
  - pcre=8.44=he6710b0_0
  - perl=5.26.2=h14c3975_0
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.2.2=py37_0
  - pycparser=2.20=py_2
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pystan=2.19.0.0=py37h962f231_0
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - pytorch=1.3.1=cuda100py37h53c1284_0
  - pytz=2020.1=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - setuptools=49.6.0=py37_1
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - swig=3.0.12=h38cdd7d_3
  - tk=8.6.10=hbc83047_0
  - torchvision=0.4.2=cuda100py37hecfc37a_0
  - tornado=6.0.4=py37h7b6447c_1
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.10.0
    - aiohttp==3.6.2
    - async-timeout==3.0.1
    - atari-py==0.2.6
    - attrs==20.2.0
    - box2d==2.3.10
    - box2d-py==2.3.8
    - cachetools==4.1.1
    - chardet==3.0.4
    - cloudpickle==1.3.0
    - future==0.18.2
    - glfw==1.12.0
    - google-auth==1.22.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.32.0
    - gym==0.17.2
    - idna==2.10
    - imageio==2.9.0
    - importlib-metadata==2.0.0
    - lockfile==0.12.2
    - markdown==3.2.2
    - multidict==4.7.6
    - oauthlib==3.1.0
    - opencv-python==4.4.0.44
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.0
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scipy==1.5.2
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - typing-extensions==3.7.4.3
    - urllib3==1.25.10
    - werkzeug==1.0.1
    - yarl==1.6.0
    - zipp==3.2.0
